# src/my_constants.py
TABLE_IGNORE_PHONE_NUMBER = "TABLE_IGNORE_PHONE_NUMBER"
TABLE_IGNORE_UID = "TABLE_IGNORE_UID"
TABLE_RESULTS = "TABLE_RESULTS"

DB_CONNECTION = "DB_CONNECTION"
DB_CONTAINER_PATH = "./repositories/db"
